from pkgutil import extend_path


if False:
    from typing import Dict, List, Tuple, Union, Optional

def _deleteOldBatchGuiPyc():
    """
    # ...we also assume that if sys.dont_write_bytecode is set, we don't need to do
    # cleanup... while this is technically not 100% foolproof, since if this is set
    # python will still READ .pyc files which may have been generated by a previous
    # run, it's a reasonably safe bet that if sys.dont_write_bytecode isn't set now,
    # and we're running from a .py, it was probably always set, and there aren't any
    # .pyc files to clean up
    """
    pass

