from typing import Any, Container, Dict, Generic, Iterable, Iterator, List, Optional, Set, Tuple, TypeVar, Union
from . import OpenMaya
import weakref
from . import _OpenMayaFX


from __builtin__ import object as _object
from __builtin__ import property as _swig_property


if False:
    from typing import Dict, List, Tuple, Union, Optional

class MDynSweptTriangle(_object):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    def area(self, *args): ...
    def normal(self, *args): ...
    def normalToPoint(self, *args): ...
    def uvPoint(self, *args): ...
    def vertex(self, *args): ...
    @staticmethod
    def className(*args, **kwargs): ...
    __dict__ : dictproxy
    
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict
    
    __weakref__ : getset_descriptor


class MFnFluid(OpenMaya.MFnDagNode):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    def create2D(self, *args): ...
    def create3D(self, *args): ...
    def density(self, *args): ...
    def emitIntoArrays(self, *args): ...
    def expandToInclude(self, *args): ...
    def falloff(self, *args): ...
    def fuel(self, *args): ...
    def getColorMode(self, *args): ...
    def getColors(self, *args): ...
    def getCoordinateMode(self, *args): ...
    def getCoordinates(self, *args): ...
    def getDensityMode(self, *args): ...
    def getDimensions(self, *args): ...
    def getFalloffMode(self, *args): ...
    def getForceAtPoint(self, *args): ...
    def getFuelMode(self, *args): ...
    def getResolution(self, *args): ...
    def getTemperatureMode(self, *args): ...
    def getVelocity(self, *args): ...
    def getVelocityMode(self, *args): ...
    def gridSize(self, *args): ...
    def index(self, *args): ...
    def isAutoResize(self, *args): ...
    def isResizeToEmitter(self, *args): ...
    def pressure(self, *args): ...
    def setColorMode(self, *args): ...
    def setCoordinateMode(self, *args): ...
    def setDensityMode(self, *args): ...
    def setFalloffMode(self, *args): ...
    def setFuelMode(self, *args): ...
    def setSize(self, *args): ...
    def setTemperatureMode(self, *args): ...
    def setVelocityMode(self, *args): ...
    def temperature(self, *args): ...
    def toGridIndex(self, *args): ...
    def type(self, *args): ...
    def updateGrid(self, *args): ...
    def velocityGridSizes(self, *args): ...
    def voxelCenterPosition(self, *args): ...
    @staticmethod
    def className(*args, **kwargs): ...
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict
    
    kCenterGradient : int
    
    kConstant : int
    
    kDynamicColorGrid : int
    
    kDynamicGrid : int
    
    kFixed : int
    
    kGradient : int
    
    kGrid : int
    
    kNegXGradient : int
    
    kNegYGradient : int
    
    kNegZGradient : int
    
    kNoFalloffGrid : int
    
    kStaticColorGrid : int
    
    kStaticFalloffGrid : int
    
    kStaticGrid : int
    
    kUseShadingColor : int
    
    kXGradient : int
    
    kYGradient : int
    
    kZGradient : int
    
    kZero : int


class floatPtr(_object):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    def assign(self, *args): ...
    def cast(self, *args): ...
    def value(self, *args): ...
    @staticmethod
    def frompointer(*args, **kwargs): ...
    __dict__ : dictproxy
    
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict
    
    __weakref__ : getset_descriptor


class MnObject(_object):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    __dict__ : dictproxy
    
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict
    
    __weakref__ : getset_descriptor


class MFnParticleSystem(OpenMaya.MFnDagNode):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    def acceleration(self, *args): ...
    def age(self, *args): ...
    def betterIllum(self, *args): ...
    def castsShadows(self, *args): ...
    def count(self, *args): ...
    def create(self, *args): ...
    def deformedParticleShape(self, *args): ...
    def disableCloudAxis(self, *args): ...
    def emission(self, *args): ...
    def emit(self, *args): ...
    def evaluateDynamics(self, *args): ...
    def flatShaded(self, *args): ...
    def getPerParticleAttribute(self, *args): ...
    def hasEmission(self, *args): ...
    def hasLifespan(self, *args): ...
    def hasOpacity(self, *args): ...
    def hasRgb(self, *args): ...
    def isDeformedParticleShape(self, *args): ...
    def isPerParticleDoubleAttribute(self, *args): ...
    def isPerParticleIntAttribute(self, *args): ...
    def isPerParticleVectorAttribute(self, *args): ...
    def isValid(self, *args): ...
    def lifespan(self, *args): ...
    def mass(self, *args): ...
    def opacity(self, *args): ...
    def originalParticleShape(self, *args): ...
    def particleIds(self, *args): ...
    def particleName(self, *args): ...
    def position(self, *args): ...
    def position0(self, *args): ...
    def position1(self, *args): ...
    def primaryVisibility(self, *args): ...
    def radius(self, *args): ...
    def radius0(self, *args): ...
    def radius1(self, *args): ...
    def receiveShadows(self, *args): ...
    def renderType(self, *args): ...
    def rgb(self, *args): ...
    def saveInitialState(self, *args): ...
    def setCount(self, *args): ...
    def setPerParticleAttribute(self, *args): ...
    def surfaceShading(self, *args): ...
    def tailSize(self, *args): ...
    def threshold(self, *args): ...
    def type(self, *args): ...
    def velocity(self, *args): ...
    def visibleInReflections(self, *args): ...
    def visibleInRefractions(self, *args): ...
    @staticmethod
    def className(*args, **kwargs): ...
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict
    
    kBlobby : int
    
    kCloud : int
    
    kMultiPoint : int
    
    kMultiStreak : int
    
    kNumeric : int
    
    kPoints : int
    
    kSpheres : int
    
    kSprites : int
    
    kStreak : int
    
    kTube : int


class doublePtr(_object):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    def assign(self, *args): ...
    def cast(self, *args): ...
    def value(self, *args): ...
    @staticmethod
    def frompointer(*args, **kwargs): ...
    __dict__ : dictproxy
    
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict
    
    __weakref__ : getset_descriptor


class MFnDynSweptGeometryData(OpenMaya.MFnData):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    def create(self, *args): ...
    def lineCount(self, *args): ...
    def sweptLine(self, *args): ...
    def sweptTriangle(self, *args): ...
    def triangleCount(self, *args): ...
    def type(self, *args): ...
    @staticmethod
    def className(*args, **kwargs): ...
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict


class uIntPtr(_object):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    def assign(self, *args): ...
    def cast(self, *args): ...
    def value(self, *args): ...
    @staticmethod
    def frompointer(*args, **kwargs): ...
    __dict__ : dictproxy
    
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict
    
    __weakref__ : getset_descriptor


class MDynamicsUtil(_object):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    @staticmethod
    def addNodeTypeToRunup(*args, **kwargs): ...
    @staticmethod
    def evalDynamics2dTexture(*args, **kwargs): ...
    @staticmethod
    def hasValidDynamics2dTexture(*args, **kwargs): ...
    @staticmethod
    def inRunup(*args, **kwargs): ...
    @staticmethod
    def removeNodeTypeFromRunup(*args, **kwargs): ...
    @staticmethod
    def runupIfRequired(*args, **kwargs): ...
    __dict__ : dictproxy
    
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict
    
    __weakref__ : getset_descriptor


class boolPtr(_object):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    def assign(self, *args): ...
    def cast(self, *args): ...
    def value(self, *args): ...
    @staticmethod
    def frompointer(*args, **kwargs): ...
    __dict__ : dictproxy
    
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict
    
    __weakref__ : getset_descriptor


class MFnPfxGeometry(OpenMaya.MFnDagNode):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    def getBoundingBox(self, *args): ...
    def getLineData(self, *args): ...
    def type(self, *args): ...
    @staticmethod
    def className(*args, **kwargs): ...
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict


class MFnField(OpenMaya.MFnDagNode):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    def attenuation(self, *args): ...
    def falloffCurve(self, *args): ...
    def getForceAtPoint(self, *args): ...
    def isFalloffCurveConstantOne(self, *args): ...
    def magnitude(self, *args): ...
    def maxDistance(self, *args): ...
    def perVertex(self, *args): ...
    def setAttenuation(self, *args): ...
    def setMagnitude(self, *args): ...
    def setMaxDistance(self, *args): ...
    def setPerVertex(self, *args): ...
    def setUseMaxDistance(self, *args): ...
    def type(self, *args): ...
    def useMaxDistance(self, *args): ...
    @staticmethod
    def className(*args, **kwargs): ...
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict


class MDynSweptLine(_object):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    def length(self, *args): ...
    def normal(self, *args): ...
    def tangent(self, *args): ...
    def vertex(self, *args): ...
    @staticmethod
    def className(*args, **kwargs): ...
    __dict__ : dictproxy
    
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict
    
    __weakref__ : getset_descriptor


class intPtr(_object):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    def assign(self, *args): ...
    def cast(self, *args): ...
    def value(self, *args): ...
    @staticmethod
    def frompointer(*args, **kwargs): ...
    __dict__ : dictproxy
    
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict
    
    __weakref__ : getset_descriptor


class shortPtr(_object):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    def assign(self, *args): ...
    def cast(self, *args): ...
    def value(self, *args): ...
    @staticmethod
    def frompointer(*args, **kwargs): ...
    __dict__ : dictproxy
    
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict
    
    __weakref__ : getset_descriptor


class MRenderLine(_object):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    def assign(self, *args): ...
    def getColor(self, *args): ...
    def getFlatness(self, *args): ...
    def getIncandescence(self, *args): ...
    def getLine(self, *args): ...
    def getParameter(self, *args): ...
    def getTransparency(self, *args): ...
    def getTwist(self, *args): ...
    def getWidth(self, *args): ...
    @staticmethod
    def className(*args, **kwargs): ...
    __dict__ : dictproxy
    
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict
    
    __weakref__ : getset_descriptor


class MFnNIdData(OpenMaya.MFnData):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    def create(self, *args): ...
    def getObjectPtr(self, *args): ...
    def type(self, *args): ...
    @staticmethod
    def className(*args, **kwargs): ...
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict


class MFnNObjectData(OpenMaya.MFnData):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    def create(self, *args): ...
    def getClothObjectPtr(self, *args): ...
    def getCollide(self, *args): ...
    def getParticleObjectPtr(self, *args): ...
    def getRigidObjectPtr(self, *args): ...
    def isCached(self, *args): ...
    def setCached(self, *args): ...
    def setObjectPtr(self, *args): ...
    def type(self, *args): ...
    @staticmethod
    def className(*args, **kwargs): ...
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict


class uCharPtr(_object):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    def assign(self, *args): ...
    def cast(self, *args): ...
    def value(self, *args): ...
    @staticmethod
    def frompointer(*args, **kwargs): ...
    __dict__ : dictproxy
    
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict
    
    __weakref__ : getset_descriptor


class MnSolver(_object):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    def addNObject(self, *args): ...
    def createNSolver(self, *args): ...
    def makeAllCollide(self, *args): ...
    def removeAllCollisions(self, *args): ...
    def removeNObject(self, *args): ...
    def setAirDensity(self, *args): ...
    def setDisabled(self, *args): ...
    def setGravity(self, *args): ...
    def setGravityDir(self, *args): ...
    def setMaxIterations(self, *args): ...
    def setStartTime(self, *args): ...
    def setSubsteps(self, *args): ...
    def setWindDir(self, *args): ...
    def setWindNoiseIntensity(self, *args): ...
    def setWindSpeed(self, *args): ...
    def solve(self, *args): ...
    __dict__ : dictproxy
    
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict
    
    __weakref__ : getset_descriptor


class MFnInstancer(OpenMaya.MFnDagNode):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    def allInstances(self, *args): ...
    def instancesForParticle(self, *args): ...
    def particleCount(self, *args): ...
    def type(self, *args): ...
    @staticmethod
    def className(*args, **kwargs): ...
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict


class MRenderLineArray(_object):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    def assign(self, *args): ...
    def deleteArray(self, *args): ...
    def length(self, *args): ...
    def renderLine(self, *args): ...
    @staticmethod
    def className(*args, **kwargs): ...
    __dict__ : dictproxy
    
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict
    
    __weakref__ : getset_descriptor


class charPtr(_object):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    def assign(self, *args): ...
    def cast(self, *args): ...
    def value(self, *args): ...
    @staticmethod
    def frompointer(*args, **kwargs): ...
    __dict__ : dictproxy
    
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict
    
    __weakref__ : getset_descriptor


class MHairSystem(_object):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    @staticmethod
    def className(*args, **kwargs): ...
    @staticmethod
    def getCollisionObject(*args, **kwargs): ...
    @staticmethod
    def getFollicle(*args, **kwargs): ...
    @staticmethod
    def registerCollisionSolverCollide(*args, **kwargs): ...
    @staticmethod
    def registerCollisionSolverPreFrame(*args, **kwargs): ...
    @staticmethod
    def registeringCallableScript(*args, **kwargs): ...
    @staticmethod
    def setRegisteringCallableScript(*args, **kwargs): ...
    @staticmethod
    def unregisterCollisionSolverCollide(*args, **kwargs): ...
    @staticmethod
    def unregisterCollisionSolverPreFrame(*args, **kwargs): ...
    __dict__ : dictproxy
    
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict
    
    __weakref__ : getset_descriptor


class MnParticle(MnObject):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    def createNParticle(self, *args): ...
    def getBounce(self, *args): ...
    def getFriction(self, *args): ...
    def getInverseMass(self, *args): ...
    def getNumVertices(self, *args): ...
    def getPositions(self, *args): ...
    def getThickness(self, *args): ...
    def getVelocities(self, *args): ...
    def setBounce(self, *args): ...
    def setCollide(self, *args): ...
    def setDamping(self, *args): ...
    def setDisableGravity(self, *args): ...
    def setDragAndLift(self, *args): ...
    def setFriction(self, *args): ...
    def setIncompressibility(self, *args): ...
    def setInverseMass(self, *args): ...
    def setLiquidRadiusScale(self, *args): ...
    def setLiquidSimulation(self, *args): ...
    def setMaxIterations(self, *args): ...
    def setMaxSelfCollisionIterations(self, *args): ...
    def setPositions(self, *args): ...
    def setRestDensity(self, *args): ...
    def setSelfCollide(self, *args): ...
    def setSelfCollideWidth(self, *args): ...
    def setSelfCollisionSoftness(self, *args): ...
    def setSurfaceTension(self, *args): ...
    def setThickness(self, *args): ...
    def setTopology(self, *args): ...
    def setVelocities(self, *args): ...
    def setViscosity(self, *args): ...
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict


class MFnNewtonField(MFnField):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    def minDistance(self, *args): ...
    def setMinDistance(self, *args): ...
    def type(self, *args): ...
    @staticmethod
    def className(*args, **kwargs): ...
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict


class MFnTurbulenceField(MFnField):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    def frequency(self, *args): ...
    def phase(self, *args): ...
    def setFrequency(self, *args): ...
    def setPhase(self, *args): ...
    def type(self, *args): ...
    @staticmethod
    def className(*args, **kwargs): ...
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict


class MFnVolumeAxisField(MFnField):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    def detailTurbulence(self, *args): ...
    def direction(self, *args): ...
    def directionalSpeed(self, *args): ...
    def invertAttenuation(self, *args): ...
    def setDirection(self, *args): ...
    def setDirectionalSpeed(self, *args): ...
    def setInvertAttenuation(self, *args): ...
    def setSpeedAlongAxis(self, *args): ...
    def setSpeedAroundAxis(self, *args): ...
    def setSpeedAwayFromAxis(self, *args): ...
    def setSpeedAwayFromCenter(self, *args): ...
    def setTurbulence(self, *args): ...
    def setTurbulenceFrequency(self, *args): ...
    def setTurbulenceOffset(self, *args): ...
    def setTurbulenceSpeed(self, *args): ...
    def speedAlongAxis(self, *args): ...
    def speedAroundAxis(self, *args): ...
    def speedAwayFromAxis(self, *args): ...
    def speedAwayFromCenter(self, *args): ...
    def turbulence(self, *args): ...
    def turbulenceFrequency(self, *args): ...
    def turbulenceOffset(self, *args): ...
    def turbulenceSpeed(self, *args): ...
    def type(self, *args): ...
    @staticmethod
    def className(*args, **kwargs): ...
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict


class MFnDragField(MFnField):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    def direction(self, *args): ...
    def setDirection(self, *args): ...
    def setUseDirection(self, *args): ...
    def type(self, *args): ...
    def useDirection(self, *args): ...
    @staticmethod
    def className(*args, **kwargs): ...
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict


class MFnUniformField(MFnField):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    def direction(self, *args): ...
    def setDirection(self, *args): ...
    def type(self, *args): ...
    @staticmethod
    def className(*args, **kwargs): ...
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict


class MFnGravityField(MFnField):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    def direction(self, *args): ...
    def setDirection(self, *args): ...
    def type(self, *args): ...
    @staticmethod
    def className(*args, **kwargs): ...
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict


class MnCloth(MnObject):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    def createNCloth(self, *args): ...
    def getBounce(self, *args): ...
    def getFriction(self, *args): ...
    def getInverseMass(self, *args): ...
    def getNumVertices(self, *args): ...
    def getPositions(self, *args): ...
    def getThickness(self, *args): ...
    def getVelocities(self, *args): ...
    def setAddCrossLinks(self, *args): ...
    def setAirTightness(self, *args): ...
    def setBendAngleDropoff(self, *args): ...
    def setBendAngleScale(self, *args): ...
    def setBendResistance(self, *args): ...
    def setBendRestAngleFromPositions(self, *args): ...
    def setBounce(self, *args): ...
    def setCollisionFlags(self, *args): ...
    def setComputeRestAngles(self, *args): ...
    def setComputeRestLength(self, *args): ...
    def setDamping(self, *args): ...
    def setDisableGravity(self, *args): ...
    def setDragAndLift(self, *args): ...
    def setFriction(self, *args): ...
    def setIncompressibility(self, *args): ...
    def setInputMeshAttractAndRigidStrength(self, *args): ...
    def setInputMeshAttractDamping(self, *args): ...
    def setInputMeshAttractPositions(self, *args): ...
    def setInverseMass(self, *args): ...
    def setLinksRestLengthFromPositions(self, *args): ...
    def setMaxIterations(self, *args): ...
    def setMaxSelfCollisionIterations(self, *args): ...
    def setPositions(self, *args): ...
    def setPressure(self, *args): ...
    def setPressureDamping(self, *args): ...
    def setPumpRate(self, *args): ...
    def setRestitutionAngle(self, *args): ...
    def setRestitutionTension(self, *args): ...
    def setSealHoles(self, *args): ...
    def setSelfCollideWidth(self, *args): ...
    def setSelfCollisionFlags(self, *args): ...
    def setSelfCollisionSoftness(self, *args): ...
    def setSelfCrossoverPush(self, *args): ...
    def setSelfTrappedCheck(self, *args): ...
    def setShearResistance(self, *args): ...
    def setStartPressure(self, *args): ...
    def setStretchAndCompressionResistance(self, *args): ...
    def setTangentialDrag(self, *args): ...
    def setThickness(self, *args): ...
    def setTopology(self, *args): ...
    def setTrackVolume(self, *args): ...
    def setVelocities(self, *args): ...
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict


class MFnRadialField(MFnField):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    def radialType(self, *args): ...
    def setType(self, *args): ...
    def type(self, *args): ...
    @staticmethod
    def className(*args, **kwargs): ...
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict


class MnRigid(MnObject):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    def createNRigid(self, *args): ...
    def getBounce(self, *args): ...
    def getFriction(self, *args): ...
    def getInverseMass(self, *args): ...
    def getNumVertices(self, *args): ...
    def getPositions(self, *args): ...
    def getThickness(self, *args): ...
    def getVelocities(self, *args): ...
    def setBounce(self, *args): ...
    def setCollisionFlags(self, *args): ...
    def setFriction(self, *args): ...
    def setPositions(self, *args): ...
    def setThickness(self, *args): ...
    def setTopology(self, *args): ...
    def setVelocities(self, *args): ...
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict


class MFnAirField(MFnField):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    def componentOnly(self, *args): ...
    def direction(self, *args): ...
    def enableSpread(self, *args): ...
    def inheritRotation(self, *args): ...
    def inheritVelocity(self, *args): ...
    def setComponentOnly(self, *args): ...
    def setDirection(self, *args): ...
    def setEnableSpread(self, *args): ...
    def setInheritRotation(self, *args): ...
    def setInheritVelocity(self, *args): ...
    def setSpeed(self, *args): ...
    def setSpread(self, *args): ...
    def speed(self, *args): ...
    def spread(self, *args): ...
    def type(self, *args): ...
    @staticmethod
    def className(*args, **kwargs): ...
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict


class MFnVortexField(MFnField):
    def __del__(self): ...
    def __getattr__(self, name): ...
    def __init__(self, *args): ...
    def __repr__(self) -> str: ...
    def __setattr__(self, name, value): ...
    def axis(self, *args): ...
    def setAxis(self, *args): ...
    def type(self, *args): ...
    @staticmethod
    def className(*args, **kwargs): ...
    __swig_destroy__ : builtin_function_or_method
    
    __swig_getmethods__ : dict
    
    __swig_setmethods__ : dict




def boolPtr_frompointer(*args, **kwargs): ...
def MFnAirField_className(*args, **kwargs): ...
def uIntPtr_swigregister(*args, **kwargs): ...
def MFnUniformField_swigregister(*args, **kwargs): ...
def MDynamicsUtil_hasValidDynamics2dTexture(*args, **kwargs): ...
def MDynamicsUtil_addNodeTypeToRunup(*args, **kwargs): ...
def MnParticle_swigregister(*args, **kwargs): ...
def MDynamicsUtil_swigregister(*args, **kwargs): ...
def floatPtr_swigregister(*args, **kwargs): ...
def MDynSweptLine_className(*args, **kwargs): ...
def MFnNObjectData_swigregister(*args, **kwargs): ...
def MHairSystem_registeringCallableScript(*args, **kwargs): ...
def MFnVortexField_className(*args, **kwargs): ...
def MFnVortexField_swigregister(*args, **kwargs): ...
def MHairSystem_unregisterCollisionSolverPreFrame(*args, **kwargs): ...
def MnCloth_swigregister(*args, **kwargs): ...
def MRenderLineArray_className(*args, **kwargs): ...
def MHairSystem_swigregister(*args, **kwargs): ...
def _swig_repr(self): ...
def MFnTurbulenceField_className(*args, **kwargs): ...
def uIntPtr_frompointer(*args, **kwargs): ...
def _swig_setattr_nondynamic(self, class_type, name, value, static='1'): ...
def MFnField_swigregister(*args, **kwargs): ...
def MFnVolumeAxisField_className(*args, **kwargs): ...
def MFnDynSweptGeometryData_swigregister(*args, **kwargs): ...
def MFnGravityField_className(*args, **kwargs): ...
def MDynamicsUtil_runupIfRequired(*args, **kwargs): ...
def MFnGravityField_swigregister(*args, **kwargs): ...
def MFnDragField_swigregister(*args, **kwargs): ...
def MFnFluid_swigregister(*args, **kwargs): ...
def MFnInstancer_swigregister(*args, **kwargs): ...
def MFnNIdData_className(*args, **kwargs): ...
def MDynamicsUtil_inRunup(*args, **kwargs): ...
def MFnNIdData_swigregister(*args, **kwargs): ...
def MnRigid_swigregister(*args, **kwargs): ...
def MFnParticleSystem_swigregister(*args, **kwargs): ...
def floatPtr_frompointer(*args, **kwargs): ...
def MHairSystem_unregisterCollisionSolverCollide(*args, **kwargs): ...
def MFnNewtonField_className(*args, **kwargs): ...
def MHairSystem_setRegisteringCallableScript(*args, **kwargs): ...
def MFnNewtonField_swigregister(*args, **kwargs): ...
def charPtr_swigregister(*args, **kwargs): ...
def MnObject_swigregister(*args, **kwargs): ...
def doublePtr_swigregister(*args, **kwargs): ...
def uCharPtr_frompointer(*args, **kwargs): ...
def _swig_getattr(self, class_type, name): ...
def MFnAirField_swigregister(*args, **kwargs): ...
def MRenderLine_swigregister(*args, **kwargs): ...
def charPtr_frompointer(*args, **kwargs): ...
def MFnInstancer_className(*args, **kwargs): ...
def weakref_proxy(*args, **kwargs):
    """
    proxy(object[, callback]) -- create a proxy object that weakly
    references 'object'.  'callback', if given, is called with a
    reference to the proxy when 'object' is about to be finalized.
    """
    ...
def MFnDynSweptGeometryData_className(*args, **kwargs): ...
def MHairSystem_className(*args, **kwargs): ...
def MRenderLineArray_swigregister(*args, **kwargs): ...
def intPtr_swigregister(*args, **kwargs): ...
def MFnNObjectData_className(*args, **kwargs): ...
def uCharPtr_swigregister(*args, **kwargs): ...
def MDynSweptTriangle_swigregister(*args, **kwargs): ...
def MFnPfxGeometry_className(*args, **kwargs): ...
def MHairSystem_registerCollisionSolverPreFrame(*args, **kwargs): ...
def MFnVolumeAxisField_swigregister(*args, **kwargs): ...
def MFnPfxGeometry_swigregister(*args, **kwargs): ...
def MHairSystem_getFollicle(*args, **kwargs): ...
def doublePtr_frompointer(*args, **kwargs): ...
def MFnParticleSystem_className(*args, **kwargs): ...
def boolPtr_swigregister(*args, **kwargs): ...
def MFnTurbulenceField_swigregister(*args, **kwargs): ...
def MRenderLine_className(*args, **kwargs): ...
def MDynamicsUtil_evalDynamics2dTexture(*args, **kwargs): ...
def MFnDragField_className(*args, **kwargs): ...
def MDynamicsUtil_removeNodeTypeFromRunup(*args, **kwargs): ...
def MnSolver_swigregister(*args, **kwargs): ...
def MFnUniformField_className(*args, **kwargs): ...
def MDynSweptLine_swigregister(*args, **kwargs): ...
def intPtr_frompointer(*args, **kwargs): ...
def MFnFluid_className(*args, **kwargs): ...
def MDynSweptTriangle_className(*args, **kwargs): ...
def shortPtr_swigregister(*args, **kwargs): ...
def MFnField_className(*args, **kwargs): ...
def MHairSystem_registerCollisionSolverCollide(*args, **kwargs): ...
def shortPtr_frompointer(*args, **kwargs): ...
def MHairSystem_getCollisionObject(*args, **kwargs): ...
def MFnRadialField_className(*args, **kwargs): ...
def MFnRadialField_swigregister(*args, **kwargs): ...
def _swig_setattr(self, class_type, name, value): ...


_newclass : int

